services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U database"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
